//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "for"
 * f1 -> "("
 * f2 -> ( ParallelAnnotation() )?
 * f3 -> Identifier()
 * f4 -> "="
 * f5 -> IntegerOrIdentifier()
 * f6 -> ";"
 * f7 -> RelopExpression()
 * f8 -> ";"
 * f9 -> UpdateLoopInductionVariable()
 * f10 -> ")"
 * f11 -> Statement()
 */
public class ForStatement implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeOptional f2;
   public Identifier f3;
   public NodeToken f4;
   public IntegerOrIdentifier f5;
   public NodeToken f6;
   public RelopExpression f7;
   public NodeToken f8;
   public UpdateLoopInductionVariable f9;
   public NodeToken f10;
   public Statement f11;

   public ForStatement(NodeToken n0, NodeToken n1, NodeOptional n2, Identifier n3, NodeToken n4, IntegerOrIdentifier n5, NodeToken n6, RelopExpression n7, NodeToken n8, UpdateLoopInductionVariable n9, NodeToken n10, Statement n11) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
      f9 = n9;
      f10 = n10;
      f11 = n11;
   }

   public ForStatement(NodeOptional n0, Identifier n1, IntegerOrIdentifier n2, RelopExpression n3, UpdateLoopInductionVariable n4, Statement n5) {
      f0 = new NodeToken("for");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = n1;
      f4 = new NodeToken("=");
      f5 = n2;
      f6 = new NodeToken(";");
      f7 = n3;
      f8 = new NodeToken(";");
      f9 = n4;
      f10 = new NodeToken(")");
      f11 = n5;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

